### DATABASE ###

spring.datasource.url: jdbc:mariadb://localhost:3306/littlecafet
spring.datasource.username: littlecafet
spring.datasource.password: hHujsGaBwsm72GT4
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto: create-drop

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect

# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.tomcat.test-while-idle: true
spring.datasource.tomcat.validation-query: SELECT 1
spring.datasource.tomcat.timeBetweenEvictionRunsMillis: 60000


#########################################################################################

### JADIRA DATETIME ###

spring.jackson.date-format: "YYYY-MM-dd"
spring.jackson.serialization.write_dates_as_timestamps: false


#########################################################################################

### LOGGING ###

spring.jpa.show-sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: trace
logging.level.org.springframework.web: INFO

#########################################################################################

### TOMCAT ###

server.port: 9000
server.ssl.enabled: true
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: Cyberspider
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat


#########################################################################################

### SECURITY ###

endpoints.enabled: false
security.headers.xss: false
server.error.whitelabel.enabled: false


#########################################################################################

### MAIL ###


spring.mail.host: smtp.heig-vd.ch
spring.mail.port: 25
spring.mail.properties.mail.smtp.auth: false


#########################################################################################

### Custom Properties ###

littlecafet.signature: "Bastian et Raphael"
littlecafet.productspath: "products.xml"




