
spring.datasource.url: jdbc:mysql://localhost:3306/littlecafet
spring.datasource.username: littlecafet
spring.datasource.password: hHujsGaBwsm72GT4


spring.jpa.properties.jadira.usertype.databaseZones: jvm
spring.jpa.properties.jadira.usertype.javaZone: jvm

spring.jackson.serialization.write_dates_as_timestamps: false

spring.jackson.serialization.write_dates_with_zone_id: true

# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.tomcat.test-while-idle: true
spring.datasource.tomcat.validation-query: SELECT 1

# Show or not log for each sql query
spring.jpa.show-sql: true

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto: create-drop

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE



logging.level.org.springframework.web: INFO

server.port: 9000
server.ssl.enabled: true
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: Cyberspider
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat


endpoints.enabled: false

security.headers.xss: false

server.error.whitelabel.enabled: false


products.path: products.xml




